### ISSUE TITLE
Can we use write.csv finally once?

### ISSUE THREAD

**Issue by murugeshmanthiramoorthi** [kalairanivignesh/MeteoAnalysisToulouse#4]
Can we directly load the data in primary memory while cleaning instead of writing it. 

Initially writing a file, and then overwriting or writing another file would create confusion in the directory. 

Do you think it would be better to write a single cleaned CSV file altogether?

**Comment by kalairanivignesh** [comment]
In our code write.csv used once and at the end. This is written at the end to validate the result and study data dictionary.
MergeAndCleanDataSets() stores in memory never writes.
